name = "vyson-url-shortener"
main = "src/index.ts"
compatibility_date = "2025-01-01"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
kv_namespaces = [
  { binding = "BLACKLIST", id = "67537b548b5c44ab8af2d74ec2aae78a" },
]
